# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'newmain.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtGui import QMovie
import sys

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(480, 320)
        MainWindow.setMinimumSize(QtCore.QSize(480, 320))
        MainWindow.setMaximumSize(QtCore.QSize(480, 320))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.C_Backframe = QtWidgets.QFrame(self.centralwidget)
        self.C_Backframe.setStyleSheet("background-color: rgb(0, 0, 0);")
        self.C_Backframe.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.C_Backframe.setFrameShadow(QtWidgets.QFrame.Raised)
        self.C_Backframe.setObjectName("C_Backframe")
        self.C_imgGota = QtWidgets.QLabel(self.C_Backframe)
        self.C_imgGota.setGeometry(QtCore.QRect(107, 10, 265, 300))
        self.C_imgGota.setMinimumSize(QtCore.QSize(265, 300))
        self.C_imgGota.setMaximumSize(QtCore.QSize(265, 300))
        self.C_imgGota.setStyleSheet("")
        self.C_imgGota.setText("")
        self.C_imgGota.setPixmap(QtGui.QPixmap("logogota.png"))
        self.C_imgGota.setObjectName("C_imgGota")
        self.C_framebtnpower = QtWidgets.QFrame(self.C_Backframe)
        self.C_framebtnpower.setGeometry(QtCore.QRect(166, 165, 147, 145))
        self.C_framebtnpower.setMinimumSize(QtCore.QSize(147, 145))
        self.C_framebtnpower.setMaximumSize(QtCore.QSize(147, 145))
        self.C_framebtnpower.setStyleSheet("background-color: rgba(153, 193, 241,100);\n"
"border:solid;\n"
"border-radius: 10px;\n"
"")
        self.C_framebtnpower.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.C_framebtnpower.setFrameShadow(QtWidgets.QFrame.Raised)
        self.C_framebtnpower.setObjectName("C_framebtnpower")
        self.V_lblpower = QtWidgets.QLabel(self.C_framebtnpower)
        self.V_lblpower.setGeometry(QtCore.QRect(36, 110, 77, 20))
        self.V_lblpower.setStyleSheet("\n"
"font: 500 15pt \"FreeSans\";\n"
"\n"
"color:rgb(255, 0, 0);\n"
"background-color: rgba(153, 193, 241,0);\n"
"")
        self.V_lblpower.setAlignment(QtCore.Qt.AlignCenter)
        self.V_lblpower.setObjectName("V_lblpower")
        self.V_btnpower = QtWidgets.QPushButton(self.C_framebtnpower)
        self.V_btnpower.setGeometry(QtCore.QRect(22, 0, 104, 100))
        self.V_btnpower.setMinimumSize(QtCore.QSize(104, 100))
        self.V_btnpower.setMaximumSize(QtCore.QSize(104, 100))
        self.V_btnpower.setStyleSheet("background-color: rgba(153, 193, 241, 0);\n"
"border-radius: 6px;    \n"
"")
        self.V_btnpower.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("poweroff.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        icon.addPixmap(QtGui.QPixmap("poweron.png"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.V_btnpower.setIcon(icon)
        self.V_btnpower.setIconSize(QtCore.QSize(100, 100))
        self.V_btnpower.setObjectName("V_btnpower")
        self.C_framecondensando = QtWidgets.QFrame(self.C_Backframe)
        self.C_framecondensando.setGeometry(QtCore.QRect(166, 10, 147, 145))
        self.C_framecondensando.setMinimumSize(QtCore.QSize(147, 145))
        self.C_framecondensando.setMaximumSize(QtCore.QSize(147, 145))
        self.C_framecondensando.setStyleSheet("background-color: rgba(153, 193, 241,100);\n"
"border:solid;\n"
"border-radius: 10px;")
        self.C_framecondensando.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.C_framecondensando.setFrameShadow(QtWidgets.QFrame.Raised)
        self.C_framecondensando.setObjectName("C_framecondensando")
        self.V_gifcondensando = QtWidgets.QLabel(self.C_framecondensando)
        self.V_gifcondensando.setGeometry(QtCore.QRect(10, 5, 127, 111))
        self.V_gifcondensando.setMinimumSize(QtCore.QSize(127, 111))
        self.V_gifcondensando.setMaximumSize(QtCore.QSize(127, 111))
        self.V_gifcondensando.setStyleSheet("background-color: rgba(153, 193, 241,0);")
        self.V_gifcondensando.setText("")
        #self.V_gifcondensando.setPixmap(QtGui.QPixmap("../../Downloads/Condensado-Render (1).gif"))
        self.V_gifcondensando.setObjectName("V_gifcondensando")
        self.C_lblcondensando = QtWidgets.QLabel(self.C_framecondensando)
        self.C_lblcondensando.setGeometry(QtCore.QRect(30, 130, 86, 12))
        self.C_lblcondensando.setMinimumSize(QtCore.QSize(86, 12))
        self.C_lblcondensando.setMaximumSize(QtCore.QSize(86, 12))
        self.C_lblcondensando.setStyleSheet("font: 30 8pt \"FreeSans\";\n"
"background-color: rgba(153, 193, 241,0);\n"
"color:rgb(255, 255, 255);\n"
"")
        self.C_lblcondensando.setObjectName("C_lblcondensando")
        self.C_frametemphum = QtWidgets.QFrame(self.C_Backframe)
        self.C_frametemphum.setGeometry(QtCore.QRect(10, 80, 147, 140))
        self.C_frametemphum.setMinimumSize(QtCore.QSize(147, 140))
        self.C_frametemphum.setMaximumSize(QtCore.QSize(147, 140))
        self.C_frametemphum.setStyleSheet("background-color: rgba(153, 193, 241,100);\n"
"border:solid;\n"
"border-radius: 10px;\n"
"")
        self.C_frametemphum.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.C_frametemphum.setFrameShadow(QtWidgets.QFrame.Raised)
        self.C_frametemphum.setObjectName("C_frametemphum")
        self.V_lbltemperatura = QtWidgets.QLabel(self.C_frametemphum)
        self.V_lbltemperatura.setGeometry(QtCore.QRect(10, 20, 88, 46))
        self.V_lbltemperatura.setMinimumSize(QtCore.QSize(88, 46))
        self.V_lbltemperatura.setMaximumSize(QtCore.QSize(88, 46))
        self.V_lbltemperatura.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.V_lbltemperatura.setStyleSheet("background-color: #05B8CC ;\n"
"color: rgb(255,255,255);\n"
"font: 750 30pt \"Ubuntu\";")
        self.V_lbltemperatura.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.V_lbltemperatura.setObjectName("V_lbltemperatura")
        self.C_lblcelcius = QtWidgets.QLabel(self.C_frametemphum)
        self.C_lblcelcius.setGeometry(QtCore.QRect(100, 20, 41, 46))
        self.C_lblcelcius.setMinimumSize(QtCore.QSize(41, 46))
        self.C_lblcelcius.setMaximumSize(QtCore.QSize(41, 46))
        self.C_lblcelcius.setStyleSheet("background-color: rgba(1,1,1,0);\n"
"color: rgb(255,255,255);\n"
"font: 750 30pt \"Ubuntu\";")
        self.C_lblcelcius.setObjectName("C_lblcelcius")
        self.V_lblhumedad = QtWidgets.QLabel(self.C_frametemphum)
        self.V_lblhumedad.setGeometry(QtCore.QRect(10, 85, 88, 46))
        self.V_lblhumedad.setMinimumSize(QtCore.QSize(88, 46))
        self.V_lblhumedad.setMaximumSize(QtCore.QSize(88, 46))
        self.V_lblhumedad.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.V_lblhumedad.setStyleSheet("background-color: #05B8CC ;\n"
"color: rgb(255,255,255);\n"
"font: 750 30pt \"Ubuntu\";")
        self.V_lblhumedad.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.V_lblhumedad.setObjectName("V_lblhumedad")
        self.C_lblporcentaje = QtWidgets.QLabel(self.C_frametemphum)
        self.C_lblporcentaje.setGeometry(QtCore.QRect(100, 85, 37, 46))
        self.C_lblporcentaje.setMinimumSize(QtCore.QSize(37, 46))
        self.C_lblporcentaje.setMaximumSize(QtCore.QSize(37, 46))
        self.C_lblporcentaje.setStyleSheet("background-color: rgba(1,1,1,0);\n"
"color: rgb(255,255,255);\n"
"font: 750 30pt \"Ubuntu\";")
        self.C_lblporcentaje.setObjectName("C_lblporcentaje")
        self.C_lblhumedad = QtWidgets.QLabel(self.C_frametemphum)
        self.C_lblhumedad.setGeometry(QtCore.QRect(20, 75, 45, 10))
        self.C_lblhumedad.setMinimumSize(QtCore.QSize(45, 10))
        self.C_lblhumedad.setMaximumSize(QtCore.QSize(45, 10))
        self.C_lblhumedad.setStyleSheet("font: 30 7pt \"FreeSans\";\n"
"background-color: rgba(153, 193, 241,0);\n"
"color:rgb(255, 255, 255);\n"
"")
        self.C_lblhumedad.setObjectName("C_lblhumedad")
        self.C_lbltemperatura = QtWidgets.QLabel(self.C_frametemphum)
        self.C_lbltemperatura.setGeometry(QtCore.QRect(20, 10, 68, 10))
        self.C_lbltemperatura.setMinimumSize(QtCore.QSize(68, 10))
        self.C_lbltemperatura.setMaximumSize(QtCore.QSize(68, 10))
        self.C_lbltemperatura.setStyleSheet("font: 30 7pt \"FreeSans\";\n"
"background-color: rgba(153, 193, 241,0);\n"
"color:rgb(255, 255, 255);\n"
"")
        self.C_lbltemperatura.setObjectName("C_lbltemperatura")
        self.C_framefiltrosestados = QtWidgets.QFrame(self.C_Backframe)
        self.C_framefiltrosestados.setGeometry(QtCore.QRect(10, 229, 147, 81))
        self.C_framefiltrosestados.setMinimumSize(QtCore.QSize(147, 81))
        self.C_framefiltrosestados.setMaximumSize(QtCore.QSize(147, 81))
        self.C_framefiltrosestados.setStyleSheet("background-color: rgba(153, 193, 241,100);\n"
"border:solid;\n"
"border-radius: 10px;\n"
"")
        self.C_framefiltrosestados.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.C_framefiltrosestados.setFrameShadow(QtWidgets.QFrame.Raised)
        self.C_framefiltrosestados.setObjectName("C_framefiltrosestados")
        self.V_lblestados = QtWidgets.QLabel(self.C_framefiltrosestados)
        self.V_lblestados.setGeometry(QtCore.QRect(18, 10, 111, 25))
        self.V_lblestados.setMinimumSize(QtCore.QSize(111, 25))
        self.V_lblestados.setMaximumSize(QtCore.QSize(111, 21))
        self.V_lblestados.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.V_lblestados.setStyleSheet("background-color: #05B8CC ;\n"
"color: rgb(255,255,255);\n"
"font: 700 7pt \"FreeSans\";\n"
"border:solid;\n"
"border-radius: 5px;\n"
"")
        self.V_lblestados.setAlignment(QtCore.Qt.AlignCenter)
        self.V_lblestados.setObjectName("V_lblestados")
        self.V_lblfiltros = QtWidgets.QLabel(self.C_framefiltrosestados)
        self.V_lblfiltros.setGeometry(QtCore.QRect(18, 46, 111, 25))
        self.V_lblfiltros.setMinimumSize(QtCore.QSize(111, 25))
        self.V_lblfiltros.setMaximumSize(QtCore.QSize(111, 21))
        self.V_lblfiltros.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.V_lblfiltros.setStyleSheet("background-color: #05B8CC ;\n"
"color: rgb(255,255,255);\n"
"font: 700 10pt \"FreeSans\";\n"
"border:solid;\n"
"border-radius: 5px;\n"
"")
        self.V_lblfiltros.setAlignment(QtCore.Qt.AlignCenter)
        self.V_lblfiltros.setObjectName("V_lblfiltros")
        self.C_framebombaactiva = QtWidgets.QFrame(self.C_Backframe)
        self.C_framebombaactiva.setGeometry(QtCore.QRect(323, 10, 147, 145))
        self.C_framebombaactiva.setMinimumSize(QtCore.QSize(147, 145))
        self.C_framebombaactiva.setMaximumSize(QtCore.QSize(147, 145))
        self.C_framebombaactiva.setStyleSheet("background-color: rgba(153, 193, 241,100);\n"
"border:solid;\n"
"border-radius: 10px;\n"
"")
        self.C_framebombaactiva.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.C_framebombaactiva.setFrameShadow(QtWidgets.QFrame.Raised)
        self.C_framebombaactiva.setObjectName("C_framebombaactiva")
        self.C_lblbombaactiva = QtWidgets.QLabel(self.C_framebombaactiva)
        self.C_lblbombaactiva.setGeometry(QtCore.QRect(30, 130, 84, 12))
        self.C_lblbombaactiva.setMinimumSize(QtCore.QSize(84, 12))
        self.C_lblbombaactiva.setMaximumSize(QtCore.QSize(84, 12))
        self.C_lblbombaactiva.setStyleSheet("font: 30 8pt \"FreeSans\";\n"
"background-color: rgba(153, 193, 241,0);\n"
"color:rgb(255, 255, 255);\n"
"")
        self.C_lblbombaactiva.setObjectName("C_lblbombaactiva")
        self.V_gifbombaactiva = QtWidgets.QLabel(self.C_framebombaactiva)
        self.V_gifbombaactiva.setGeometry(QtCore.QRect(10, 10, 127, 111))
        self.V_gifbombaactiva.setMinimumSize(QtCore.QSize(127, 111))
        self.V_gifbombaactiva.setMaximumSize(QtCore.QSize(127, 111))
        self.V_gifbombaactiva.setStyleSheet("background-color: rgba(153, 193, 241,0);")
        self.V_gifbombaactiva.setText("")
        #self.V_gifbombaactiva.setPixmap(QtGui.QPixmap("../../Downloads/Bomba-Activa (1).gif"))
        self.V_gifbombaactiva.setObjectName("V_gifbombaactiva")
        self.C_framenivelestanques = QtWidgets.QFrame(self.C_Backframe)
        self.C_framenivelestanques.setGeometry(QtCore.QRect(323, 165, 147, 145))
        self.C_framenivelestanques.setMinimumSize(QtCore.QSize(147, 145))
        self.C_framenivelestanques.setMaximumSize(QtCore.QSize(147, 145))
        self.C_framenivelestanques.setStyleSheet("background-color: rgba(153, 193, 241,100);\n"
"border:solid;\n"
"border-radius: 10px;\n"
"")
        self.C_framenivelestanques.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.C_framenivelestanques.setFrameShadow(QtWidgets.QFrame.Raised)
        self.C_framenivelestanques.setObjectName("C_framenivelestanques")
        self.V_nvlsuperior = QtWidgets.QProgressBar(self.C_framenivelestanques)
        self.V_nvlsuperior.setGeometry(QtCore.QRect(10, 30, 57, 90))
        self.V_nvlsuperior.setMinimumSize(QtCore.QSize(57, 90))
        self.V_nvlsuperior.setMaximumSize(QtCore.QSize(57, 90))
        self.V_nvlsuperior.setAutoFillBackground(False)
        self.V_nvlsuperior.setStyleSheet("QProgressBar {\n"
"    border: 1.5px solid #05B8CC;\n"
"    border-radius: 6px;\n"
"    background-color:rgba(0, 0, 0, 0)\n"
"}\n"
"\n"
"QProgressBar::chunk {\n"
"    background-color:#05B8CC ;\n"
"    margin: 0.5px;\n"
"}\n"
"")
        self.V_nvlsuperior.setProperty("value", 40)
        self.V_nvlsuperior.setTextVisible(False)
        self.V_nvlsuperior.setOrientation(QtCore.Qt.Vertical)
        self.V_nvlsuperior.setObjectName("V_nvlsuperior")
        self.V_nvlsuperior_2 = QtWidgets.QProgressBar(self.C_framenivelestanques)
        self.V_nvlsuperior_2.setGeometry(QtCore.QRect(80, 30, 57, 90))
        self.V_nvlsuperior_2.setMinimumSize(QtCore.QSize(57, 90))
        self.V_nvlsuperior_2.setMaximumSize(QtCore.QSize(57, 90))
        self.V_nvlsuperior_2.setAutoFillBackground(False)
        self.V_nvlsuperior_2.setStyleSheet("QProgressBar {\n"
"    border: 1.5px solid #05B8CC;\n"
"    border-radius: 6px;\n"
"    background-color:rgba(0, 0, 0, 0)\n"
"}\n"
"\n"
"QProgressBar::chunk {\n"
"    background-color:#05B8CC ;\n"
"    margin: 0.5px;\n"
"}\n"
"")
        self.V_nvlsuperior_2.setProperty("value", 40)
        self.V_nvlsuperior_2.setTextVisible(False)
        self.V_nvlsuperior_2.setOrientation(QtCore.Qt.Vertical)
        self.V_nvlsuperior_2.setObjectName("V_nvlsuperior_2")
        self.C_lblnivelestanques = QtWidgets.QLabel(self.C_framenivelestanques)
        self.C_lblnivelestanques.setGeometry(QtCore.QRect(21, 10, 105, 12))
        self.C_lblnivelestanques.setMinimumSize(QtCore.QSize(105, 12))
        self.C_lblnivelestanques.setMaximumSize(QtCore.QSize(105, 12))
        self.C_lblnivelestanques.setStyleSheet("font: 30 8pt \"FreeSans\";\n"
"background-color: rgba(153, 193, 241,0);\n"
"color:rgb(255, 255, 255);\n"
"")
        self.C_lblnivelestanques.setObjectName("C_lblnivelestanques")
        self.C_lblinferior = QtWidgets.QLabel(self.C_framenivelestanques)
        self.C_lblinferior.setGeometry(QtCore.QRect(18, 128, 43, 10))
        self.C_lblinferior.setMinimumSize(QtCore.QSize(43, 10))
        self.C_lblinferior.setMaximumSize(QtCore.QSize(43, 10))
        self.C_lblinferior.setStyleSheet("font: 30 7pt \"FreeSans\";\n"
"background-color: rgba(153, 193, 241,0);\n"
"color:rgb(255, 255, 255);\n"
"")
        self.C_lblinferior.setObjectName("C_lblinferior")
        self.C_lblsuperior = QtWidgets.QLabel(self.C_framenivelestanques)
        self.C_lblsuperior.setGeometry(QtCore.QRect(86, 128, 47, 10))
        self.C_lblsuperior.setMinimumSize(QtCore.QSize(47, 10))
        self.C_lblsuperior.setMaximumSize(QtCore.QSize(47, 10))
        self.C_lblsuperior.setStyleSheet("font: 30 7pt \"FreeSans\";\n"
"background-color: rgba(153, 193, 241,0);\n"
"color:rgb(255, 255, 255);\n"
"")
        self.C_lblsuperior.setObjectName("C_lblsuperior")
        self.C_imgnube = QtWidgets.QLabel(self.C_Backframe)
        self.C_imgnube.setGeometry(QtCore.QRect(48, 10, 70, 57))
        self.C_imgnube.setMinimumSize(QtCore.QSize(70, 57))
        self.C_imgnube.setMaximumSize(QtCore.QSize(70, 57))
        self.C_imgnube.setText("")
        self.C_imgnube.setPixmap(QtGui.QPixmap("logonube.png"))
        self.C_imgnube.setObjectName("C_imgnube")
        self.verticalLayout.addWidget(self.C_Backframe)
        MainWindow.setCentralWidget(self.centralwidget)

        self.movie = QMovie("Condensado-Render (1).gif")
        self.V_gifcondensando.setMovie(self.movie)
        self.movie.start()
        self.movie.setPaused(False)

        self.movie2 = QMovie("Bomba-Activa (1).gif")
        self.V_gifbombaactiva.setMovie(self.movie2)
        self.movie2.start()
        self.movie2.setPaused(False)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.V_lblpower.setText(_translate("MainWindow", "POWER"))
        self.C_lblcondensando.setText(_translate("MainWindow", "CONDENSANDO"))
        self.V_lbltemperatura.setText(_translate("MainWindow", "5"))
        self.C_lblcelcius.setText(_translate("MainWindow", "°C"))
        self.V_lblhumedad.setText(_translate("MainWindow", "5"))
        self.C_lblporcentaje.setText(_translate("MainWindow", "%"))
        self.C_lblhumedad.setText(_translate("MainWindow", "HUMEDAD"))
        self.C_lbltemperatura.setText(_translate("MainWindow", "TEMPERATURA"))
        self.V_lblestados.setText(_translate("MainWindow", "DESCONGELAMIENTO"))
        self.V_lblfiltros.setText(_translate("MainWindow", "Agua F: 0"))
        self.C_lblbombaactiva.setText(_translate("MainWindow", "BOMBA ACTIVA"))
        self.C_lblnivelestanques.setText(_translate("MainWindow", "NIVEL DE TANQUES"))
        self.C_lblinferior.setText(_translate("MainWindow", "INFERIOR"))
        self.C_lblsuperior.setText(_translate("MainWindow", "SUPERIOR"))
        
   

if __name__ == "__main__":
    app = QtWidgets.QApplication(sys.argv)
    window = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(window)
    window.show()
    sys.exit(app.exec_())
